name: copy-generated-to-main

on:
  workflow_run:
    workflows: ["generate-user-scripts"]
    types:
    - completed
    branches:
    - develop

jobs:
  copy-generated:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: develop
        path: develop
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}
        ref: main
        path: main
    - name: Copy Files
      working-directory: main
      run: |
        set -e
        ls -sl ..
        cp -r ../develop/generated ./generated
        git add .
        if ! git diff-index --quiet HEAD --; then
          git commit -m "copying generated user scripts for '${BRANCH}' branch to main"
          git push
        else
          echo "No Changes to commit!"
        fi
