name: generate-user-scripts

on:
  push:
    branches:
    - main
    - develop
    paths-ignore:
    - 'README.md'
    - 'generated/**'
    
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          ref: ${{ github.head_ref }}
      - name: Generate
        run: |
          set -e
          shopt -s globstar
          
          export BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Current Branch: $BRANCH"

          rm -rf ./generated/$BRANCH
          WORKING_DIR=./generated/$BRANCH/scripts
          mkdir -p $WORKING_DIR

          for i in **/*.template; do
            templateFilePath=$(realpath $i)
            parentdir="$(dirname "$templateFilePath")"
            parentdir=${parentdir##*/}
            filename=$(basename -- "$templateFilePath")
            filename=${filename%.*}
            mkdir -p $WORKING_DIR/$parentdir
            pushd $WORKING_DIR/$parentdir
              cat $templateFilePath | envsubst > $filename
            popd
          done

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          
          git update-index -q --refresh
          
          if ! git diff-index --quiet HEAD --; then
            echo "Commiting changes to '${BRANCH}' branch..."
            git commit -m "generated user scripts for '${BRANCH}' branch"
            git push
            echo Done!
          else
            echo "No Changes to commit!"
          fi

