name: Generate user scripts for git pages

on:
  push:
    branches:
    - main
    - develop
    paths-ignore:
    - 'README.md'
    - 'generated/**'
env:
  BRANCH: ${{ github.head_ref }}

jobs:
  generate:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          ref: ${{ env.BRANCH }}
      - name: Generate
        run: |
          set -e
          shopt -s globstar
          
          #export BRANCH=$(git branch --show-current)
          echo "Current Branch: $BRANCH"

          rm -rf ./generated/$BRANCH
          WORKING_DIR=./generated/$BRANCH/scripts
          mkdir -p $WORKING_DIR

          for i in **/*.template; do
            templateFilePath=$(realpath $i)
            parentdir="$(dirname "$templateFilePath")"
            parentdir=${parentdir##*/}
            filename=$(basename -- "$templateFilePath")
            filename=${filename%.*}
            mkdir -p $WORKING_DIR/$parentdir
            pushd $WORKING_DIR/$parentdir
              cat $templateFilePath | envsubst > $filename
            popd
          done

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          
          commit=
          
          git update-index -q --refresh
          
          if ! git diff-index --quiet HEAD --; then
            echo "Commiting changes to '${BRANCH}' branch..."
            git commit -m "generated user scripts for '${BRANCH}' branch"
            commit=$(git rev-parse HEAD)
            git push
            echo Done!
          else
            echo "No Changes to commit!"
          fi
          
      - name: Checkout
        uses: actions/checkout@v3        
        if: ${{ success() && github.head_ref != 'main' }}
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          ref: main
      - name: Copy generated to main
        if: ${{ success() && github.head_ref != 'main' }}
        run: |
          set -e
          echo branch: '$BRANCH'
          git restore -s $BRANCH -SW -- ./generated/**
          git update-index -q --refresh
          if ! git diff-index --quiet HEAD --; then
            git commit -m "copying generated user scripts for '${BRANCH}' branch to main"
            git push
          else
            echo "No Changes to commit!"
          fi
          
          
          

